// not used, should be removed after figuring out what to do with

export const REGISTERED_KEYS = [
  'friendlytime.',
  'navigator.',
  'cancel',
  'catalog.',
  '.group',
  'widget.',
  'widgets.',
  'unique.',
  'countdown_clock_unit_',
  'mod.',
  'notifications.',
  '.notification',
  'connection.',
  'opening.',
  'login.',
  'maintenance.',
  'achievements.',
  'inventory.',
  'generic.',
  'friendlist.',
  'infostand.',
  'help.',
  'people.',
  'catalog_',
  'roomad.',
  'buy',
  'avatareditor.',
  'campaign.',
  'quests.',
  'room.',
  'messenger.',
  'memenu.'
]
